coldemail/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('email/', include('sendingemail.urls')),
    path('email-data/', include('email_data.urls')),
    path('generator/', include('generator_message.urls')),
    path('', include('dashboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_data/urls.py
from django.urls import path
from . import views

app_name = 'email_data'

urlpatterns = [
    path('', views.email_list, name='email_list'),
    path('email/new/', views.email_create, name='email_create'),  # Pastikan URL pattern untuk create ada di sini
    path('email/<str:email>/edit/', views.email_update, name='email_update'),
    path('email/<str:email>/delete/', views.email_delete, name='email_delete'),
    path('api/emails/', views.get_all_emails, name='get_all_emails'),
    path('api/emails/department/<str:department>/', views.get_emails_by_department, name='get_emails_by_department'),
]

email_data/models.py
import uuid
from django.db import models

class EmailData(models.Model):
    DEPARTMENT_CHOICES = [
        ('HR', 'Devisi HR'),
        ('RnD', 'Devisi RnD'),
        ('Media', 'Devisi Media Informasi'),
        ('Engineering', 'Devisi Engineering'),
        ('Customers', 'Customers'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nama = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    group = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES)

    def __str__(self):
        return self.nama

email_data/forms.py
from django import forms
from .models import EmailData

class EmailDataForm(forms.ModelForm):
    class Meta:
        model = EmailData
        fields = ['nama', 'email', 'group']

    def __init__(self, *args, **kwargs):
        super(EmailDataForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if self.instance.pk is None:
            if EmailData.objects.filter(email=email).exists():
                raise forms.ValidationError('Email data with this Email already exists.')
        else:
            if EmailData.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('Email data with this Email already exists.')
        return email

email_data/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import EmailDataForm
from django.http import JsonResponse
from .models import EmailData
from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required(login_url='/auth/login/')
def email_list(request):
    emails = EmailData.objects.all()
    return render(request, 'email_list.html', {'emails': emails})

@staff_member_required(login_url='/auth/login/')
def email_detail(request, email):
    email_data = get_object_or_404(EmailData, email=email)
    return render(request, 'email_detail.html', {'email_data': email_data})

@staff_member_required(login_url='/auth/login/')
def email_create(request):
    if request.method == "POST":
        form = EmailDataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('email_data:email_list')
    else:
        form = EmailDataForm()
    return render(request, 'email_form.html', {'form': form})

@staff_member_required(login_url='/auth/login/')
def email_update(request, email):
    email_data = get_object_or_404(EmailData, email=email)
    if request.method == "POST":
        form = EmailDataForm(request.POST, instance=email_data)
        if form.is_valid():
            form.save()
            return redirect('email_data:email_list')
    else:
        form = EmailDataForm(instance=email_data)
    return render(request, 'email_form.html', {'form': form})

@staff_member_required(login_url='/auth/login/')
def email_delete(request, email):
    email_data = get_object_or_404(EmailData, email=email)
    if request.method == "POST":
        email_data.delete()
        return redirect('email_data:email_list')
    return render(request, 'email_confirm_delete.html', {'email_data': email_data})


@staff_member_required(login_url='/auth/login/')
def get_all_emails(request):
    emails = EmailData.objects.all().values('nama', 'email', 'created_at', 'updated_at', 'group')
    return JsonResponse(list(emails), safe=False)

@staff_member_required(login_url='/auth/login/')
def get_emails_by_department(request, department):
    emails = EmailData.objects.filter(group=department).values('nama', 'email', 'created_at', 'updated_at', 'group')
    return JsonResponse(list(emails), safe=False)

email_data/templates/email_form.html
{% extends 'base.html' %}

{% block meta %}
<title>{% if form.email.value %}Edit Email{% else %}Create Email{% endif %}</title>
{% endblock meta %}

{% block content %}
<div class="max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden m-10">
    <div class="px-6 py-4">
        <h1 class="text-2xl font-bold mb-4">{% if form.email.value %}Edit Email{% else %}Create Email{% endif %}</h1>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            <div>
                <label class="block text-sm font-semibold text-gray-950" for="{{ form.nama.id_for_label }}">Name</label>
                <div class="mt-1">
                    <input type="text" name="{{ form.nama.html_name }}" id="{{ form.nama.id_for_label }}"
                        value="{{ form.nama.value|default_if_none:'' }}"
                        class="input input-bordered w-full focus:border-orange-600 focus:ring-orange-600" required>

                </div>
            </div>
            <div>
                <label class="block text-sm font-semibold text-gray-950"
                    for="{{ form.email.id_for_label }}">Email</label>
                <div class="mt-1">
                    <input type="email" name="{{ form.email.html_name }}" id="{{ form.email.id_for_label }}"
                        value="{{ form.email.value|default_if_none:'' }}" class="input input-bordered w-full" required>

                </div>
            </div>
            <div>
                <label class="block text-sm font-semibold text-gray-950"
                    for="{{ form.group.id_for_label }}">Group</label>
                <div class="mt-1">
                    <select name="{{ form.group.html_name }}" id="{{ form.group.id_for_label }}"
                        class="input input-bordered w-full">
                        {% for value, label in form.group.field.choices %}
                        {% if form.group.value|stringformat:"s" == value|stringformat:"s" %}
                        <option value="{{ value }}" selected>{{ label }}</option>
                        {% else %}
                        <option value="{{ value }}">{{ label }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="flex justify-end gap-2">
                <button type="submit"
                    class="btn bg-orange-500 text-white px-4 py-2 rounded-lg hover:bg-orange-600 hover:text-orange-100">Save</button>
                <a href="{% url 'email_data:email_list' %}"
                    class="btn bg-red-600 text-white hover:bg-red-700 hover:text-red-100 rounded-lg">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

email_data/templates/email_list.html
{% extends 'base.html' %}

{% block meta %}
<title>Email List</title>
{% endblock meta %}

{% block content %}
<div class="text-2xl font-semibold m-10">Email List</div>
<table class="table" id="emailTable">
    <thead class="bg-gray-950 text-white">
        <tr>
            <th></th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for email in emails %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td class="text-orange-600">{{ email.nama }} </td>
            <td>{{ email.email }}</td>
            <td>{{ email.group }}</td>
            <td>
                <a href="{% url 'email_data:email_update' email.email %}"
                    class="btn btn-sm bg-orange-500 hover:bg-orange-600 hover:text-orange-100 rounded-lg text-white">Edit</a>
                <button
                    class="btn btn-sm bg-red-600 hover:bg-red-700 hover:text-red-100 rounded-lg text-white delete-link"
                    onclick="showDeleteModal(event, '{{ email.email }}')">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<dialog id="my_modal_1" class="modal">
    <div class="modal-box">
        <h3 class="font-bold text-lg">Confirm Deletion</h3>
        <p class="py-4">Are you sure you want to delete <span id="deleteEmail"></span>?</p>
        <div class="modal-action">
            <form method="post" id="deleteForm">
                {% csrf_token %}
                <button class="btn bg-red-600 hover:bg-red-700 hover:text-red-100 rounded-lg text-white"
                    id="confirmDeleteButton">Confirm</button>
                <button type="button" class="btn btn-neutral rounded-lg text-white"
                    onclick="my_modal_1.close()">Cancel</button>
            </form>
        </div>
    </div>
</dialog>

<a href="{% url 'email_data:email_create' %}"
    class="btn btn-base bg-orange-500 hover:bg-orange-600 hover:text-orange-100 ml-10 mb-20 text-white rounded-lg p-3">Add
    Data +</a>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    $(document).ready(function () {
        var table = $('#emailTable').DataTable({
            "lengthChange": false,
            "pageLength": 10,
            "info": false,
            "language": {
                "paginate": {
                    "previous": "Prev",
                    "next": "Next"
                }
            }
        });
    });

    function showDeleteModal(event, email) {
        event.preventDefault();
        $('#deleteEmail').text(email);
        my_modal_1.showModal();
    }

    $('#confirmDeleteButton').on('click', function (event) {
        event.preventDefault();
        var email = $('#deleteEmail').text();
        var url = '/email-data/email/' + encodeURIComponent(email) + '/delete/';
        $.ajax({
            url: url,
            type: 'POST',
            data: $('#deleteForm').serialize(),
            success: function (response) {
                my_modal_1.close();
                Swal.fire({
                    icon: 'success',
                    title: 'Deleted!',
                    text: 'The email has been deleted successfully.',
                    confirmButtonColor: '#DD6B20'
                }).then(() => {
                    location.reload();
                });
            },
            error: function (xhr, status, error) {
                console.error(xhr.responseText);
                my_modal_1.close();
                Swal.fire({
                    icon: 'error',
                    title: 'Error!',
                    text: 'An error occurred while trying to delete the email. Please try again.',
                    confirmButtonColor: '#d33'
                });
            }
        });
    });
</script>

<style>
    .dt-container {
        margin: 2.5rem;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        padding: 5px 10px;
        margin-right: 5px;
        border: 1px solid #ccc;
        border-radius: 3px;
        background-color: #fff;
        color: #333;
    }

    /* Style untuk input pencarian */
    .dt-search {
        margin-bottom: 10px;
        /* Tambahkan margin agar tidak rapat dengan tabel */
        display: flex;
        align-items: center;
        width: 100%;
    }

    .dt-search label {
        margin-right: 10px;
        font-weight: 600;
    }

    .dt-search input[type="search"] {
        width: 20%;
    }

    .dt-search input[type="search"]:focus {
        border-color: #DD6B20;
        /* Warna fokus oranye */
        outline: none;
        box-shadow: 0 0 0 1px #DD6B20;
    }
</style>
{% endblock content %}