authentication/urls.py
from django.urls import path
from .views import login_user, logout_user, register_user
from django.contrib.auth import views
from django.urls import reverse_lazy

app_name = 'authentication'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_user, name='register'),
    path('password_reset/', views.PasswordResetView.as_view(template_name="Password_Reset_Form.html",   email_template_name='Password_Reset_Email.html',
                                              success_url=reverse_lazy('authentication:password_reset_done')), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name="Password_Reset_Done.html"), name='password_reset_done'),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(template_name="Password_Reset_Confirm.html", success_url=reverse_lazy('authentication:password_reset_complete')),
        name="password_reset_confirm",
    ),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name="Password_Reset_Complete.html"), name='password_reset_complete'),
]

coldemail/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('email/', include('sendingemail.urls')),
    path('email-data/', include('email_data.urls')),
    path('generator/', include('generator_message.urls')),
    path('', include('dashboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

email_data/urls.py
from django.urls import path
from . import views

app_name = 'email_data'

urlpatterns = [
    path('', views.email_list, name='email_list'),
    path('email/new/', views.email_create, name='email_create'),  # Pastikan URL pattern untuk create ada di sini
    path('email/<str:email>/edit/', views.email_update, name='email_update'),
    path('email/<str:email>/delete/', views.email_delete, name='email_delete'),
    path('api/emails/', views.get_all_emails, name='get_all_emails'),
    path('api/emails/department/<str:department>/', views.get_emails_by_department, name='get_emails_by_department'),
]

generator_message/urls.py
from django.urls import path
from . import views


app_name = 'generator_message'

urlpatterns = [
    path('', views.generator_view , name="generator"),
    path('chat/', views.chat, name='chat'),
]

email_data/models.py
import uuid
from django.db import models

class EmailData(models.Model):
    DEPARTMENT_CHOICES = [
        ('HR', 'Devisi HR'),
        ('RnD', 'Devisi RnD'),
        ('Media', 'Devisi Media Informasi'),
        ('Engineering', 'Devisi Engineering'),
        ('Customers', 'Customers'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nama = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    group = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES)

    def __str__(self):
        return self.nama

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="corporate">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" />
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

    <style>
        #id_email,
        #id_new_password1,
        #id_new_password2 {
            width: 100%;
            padding: 0.5rem 1rem;
            font-size: 1rem;
            border-radius: 0.25rem;
            border: 1px solid #ccc;
        }

        html,
        body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }

        footer {
            flex-shrink: 0;
        }
    </style>
    {% tailwind_css %} {% block meta %}
    <title>{% block title %}{% endblock title %}</title>
    {% endblock meta %}

</head>

<body class="p-0 m-0 box-border bg-gray-50">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <header>
        <div class="navbar bg-gradient-to-b from-gray-950 to-gray-800 shadow-2xl">
            <div class="navbar-start">
                <div class="dropdown">
                    <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                            stroke="white">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4 6h16M4 12h8m-8 6h16" />
                        </svg>
                    </div>
                    <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                        <li>
                            <a href="/" class="{% if request.path == '/' %} text-orange-600 {% endif %}">Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'generator_message:generator' %}"
                                class="{% if request.path == '/generator/' %} text-orange-600 {% endif %}">Message
                                Generator</a>
                        </li>
                        <li>
                            <a href="{% url 'email_data:email_list' %}"
                                class="{% if request.path == '/email-data/' %} text-orange-600 {% endif %}">Email
                                Data</a>
                        </li>
                    </ul>
                </div>
                <a class="text-xl font-semibold ml-5"><span><img width="200 rem"
                            src="https://storage.googleapis.com/algonetwork/logo%20v1%20white%404x.png"
                            class="text-black" alt="logo" /></span></a>
            </div>

            <div class="navbar-center hidden lg:flex">
                <ul class="menu menu-horizontal px-1">
                    <li>
                        <a href="/"
                            class="{% if request.path == '/' %} text-orange-600 {% else %} text-white {% endif %}">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'generator_message:generator' %}"
                            class="{% if request.path == '/generator/' %} text-orange-600 {% else %} text-white {% endif %}">Message
                            Generator</a>
                    </li>
                    <li>
                        <a href="{% url 'email_data:email_list' %}"
                            class="{% if request.path == '/email-data/' %} text-orange-600 {% else %} text-white {% endif %}">Email
                            Data</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-end gap-1">
                {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <a href="{% url 'authentication:register' %}"
                    class="btn bg-orange-500 hover:bg-orange-600 hover:text-orange-100 font-semibold text-white rounded-lg">Admin
                    +</a>
                {% endif %}
                <a href="{% url 'authentication:logout' %}"
                    class="btn bg-red-600 hover:bg-red-700 hover:text-red-100 text-white rounded-lg">Logout</a>

                {% else %}

                <a href="{% url 'authentication:login' %}"
                    class="btn bg-orange-500 hover:bg-orange-600 hover:text-orange-100 font-semibold rounded-lg text-white">Login</a>
                {% endif %}
            </div>
        </div>
    </header>

    <main>{% block content %} {% endblock content %}</main>

    <footer class="bottom-0 w-full flex justify-center">
        <div class="bg-gradient-to-b from-gray-800 to-gray-950 shadow-2xl w-full">
            <div class="border border-blue-200"></div>
            <div class="flex flex-col items-center">
                <div class="flex flex-col md:flex-row justify-center gap-10 items-center my-10">
                    <span class="flex flex-col items-center md:items-start">
                        <img width="200 rem" src="https://storage.googleapis.com/algonetwork/logo%20v1%20white%404x.png"
                            class="text-black" alt="logo" />
                        <h1 class="text-white font-semibold text-center md:text-left mt-4 md:mt-0 md:ml-14">
                            PT. Algonacci Sobat Nusantara
                        </h1>
                    </span>

                    <div class="flex flex-col items-center md:items-start mt-10 md:mt-0 md:ml-40">
                        <h6 class="text-white text-center md:text-left">A Palugada Company Based in Jakarta</h6>
                        <p class="text-white mt-1 text-center md:text-left">
                            Jl. Letjen S. Parman No.28 Grogol Petamburan
                        </p>
                        <p class="text-white mt-1 text-center md:text-left">
                            Jakarta Barat Daerah Khusus Ibukota Jakarta 11470
                        </p>
                    </div>
                </div>

                <h1 class="text-white my-5 text-center">
                    <span class="text-blue-500">©</span> Algo Network <span class="text-orange-500">2024</span> - <span
                        class="text-green-500">Crafted with C241-CE02 ❤️</span>
                </h1>
            </div>
        </div>
    </footer>
</body>

</html>