coldemail/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('email/', include('sendingemail.urls')),
    path('email-data/', include('email_data.urls')),
    path('generator/', include('generator_message.urls')),
    path('', include('dashboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import home, get_sent_emails, get_scheduled_emails, get_email_details, edit_schedule_email_view, delete_email


app_name = 'dashboard'

urlpatterns = [
    path('', home , name="home"),
    path('emails/sent/', get_sent_emails, name='get_sent_emails'),
    path('emails/scheduled/', get_scheduled_emails, name='get_scheduled_emails'),
    path('emails/detail/<uuid:pk>/', get_email_details, name='get_email_details'),
    path('edit-schedule-email/<uuid:pk>/', edit_schedule_email_view, name='edit_schedule_email'),
    path('emails/delete/<uuid:pk>/', delete_email, name='delete_email'),
  
]

sendingemail/models.py
import uuid
from django.db import models
from email_data.models import EmailData
from ckeditor.fields import RichTextField
from authentication.models import CustomUser 

class EmailSchedule(models.Model):
    DEPARTMENT_CHOICES = EmailData.DEPARTMENT_CHOICES

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='email_schedules')
    department = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES)
    subject = models.CharField(max_length=255, null=True)
    content = RichTextField(blank=True, null=True) 
    schedule_time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status_sent = models.BooleanField(default=False) 

    def __str__(self):
        return f"{self.subject} - {self.user.email}" 

dashboard/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from sendingemail.models import EmailSchedule
from django_celery_beat.models import PeriodicTask, CrontabSchedule
from sendingemail.forms import EmailScheduleForm
from django.utils import timezone
import json
import pytz

from django.views.decorators.csrf import csrf_exempt

@staff_member_required(login_url='/auth/login/')
def home(request):
    return render(request, "email_manager.html")

def format_schedule_time(utc_time):
    jakarta_timezone = pytz.timezone('Asia/Jakarta')
    return utc_time.astimezone(jakarta_timezone)


@staff_member_required(login_url='/auth/login/')
def get_sent_emails(request):
    sent_emails = EmailSchedule.objects.filter(schedule_time__lte=timezone.now(), user=request.user, status_sent=True)
    data = {
        'emails': [{'id': email.id, 'subject': email.subject, 'schedule_time': format_schedule_time(email.schedule_time).strftime("%d-%m-%Y %H:%M:%S")} for email in sent_emails],
    }
    return JsonResponse(data)

@staff_member_required(login_url='/auth/login/')
def get_scheduled_emails(request):
    scheduled_emails = EmailSchedule.objects.filter(schedule_time__gt=timezone.now(), user=request.user, status_sent=False)
    data = {
        'emails': [{'id': email.id, 'subject': email.subject, 'schedule_time': format_schedule_time(email.schedule_time).strftime("%d-%m-%Y %H:%M:%S")} for email in scheduled_emails],
    }
    return JsonResponse(data)


@staff_member_required(login_url='/auth/login/')
def get_email_details(request, pk):
    email = get_object_or_404(EmailSchedule, pk=pk)
    email_details = {
        'id': str(email.id),
        'department': email.department,
        'subject': email.subject,
        'content': email.content,
        'schedule_time': format_schedule_time(email.schedule_time).strftime("%d-%m-%Y %H:%M:%S")
    }
    return JsonResponse(email_details)


@staff_member_required(login_url='/auth/login/')
def edit_schedule_email_view(request, pk):
    email_schedule = get_object_or_404(EmailSchedule, pk=pk)
    old_department = email_schedule.department
    old_schedule_time = email_schedule.schedule_time

    if request.method == 'POST':
        form = EmailScheduleForm(request.POST, instance=email_schedule)
        
        if form.is_valid():
            email_schedule = form.save(commit=False)
            schedule_time = email_schedule.schedule_time

            # Update the periodic task with new crontab schedule and args
            day_of_week = schedule_time.weekday() + 1
            if day_of_week == 7:
                day_of_week = 0

            schedule, created = CrontabSchedule.objects.get_or_create(
                minute=schedule_time.minute,
                hour=schedule_time.hour,
                day_of_month=schedule_time.day,
                month_of_year=schedule_time.month,
                day_of_week=day_of_week
            )

            # Get the old periodic task and update it
            old_task_name = f"Send email to {old_department} at {format_schedule_time(old_schedule_time)}"
            periodic_task = get_object_or_404(PeriodicTask, name=old_task_name)
            
            # Save changes to email_schedule first
            email_schedule.save()

            # Update the name, crontab, args, and expiration
            new_task_name = f"Send email to {email_schedule.department} at {format_schedule_time(schedule_time)}"
            periodic_task.name = new_task_name
            periodic_task.crontab = schedule
            periodic_task.args = json.dumps([email_schedule.department, email_schedule.subject, email_schedule.content, str(email_schedule.id)])
            periodic_task.expires = schedule_time + timezone.timedelta(minutes=10)
            periodic_task.save()

            return JsonResponse({'success': True, 'message': 'Email schedule updated successfully'})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = EmailScheduleForm(instance=email_schedule)
    return render(request, 'edit_schedule_email.html', {'form': form, 'email_schedule': email_schedule})


@staff_member_required(login_url='/auth/login/')
@csrf_exempt
def delete_email(request, pk):
    if request.method == 'POST':
        email = get_object_or_404(EmailSchedule, pk=pk)

  
        periodic_task = PeriodicTask.objects.filter(
            name=f"Send email to {email.department} at {format_schedule_time(email.schedule_time)}"
        ).first()

        if not periodic_task:
            email.delete()
            return JsonResponse({'status': 'success'}, status=200)
        
        email.delete()
        periodic_task.delete()
        return JsonResponse({'status': 'success'}, status=200)
    else:
        return JsonResponse({'status': 'failed', 'message': 'Invalid request'}, status=400)

dashboard/templates/edit_schedule_email.html
{% extends 'base.html' %}

{% block meta %}
<title>Edit Message</title>
{% endblock meta %}

{% block content %}
<div class="flex justify-center m-10">
    <form method="post" id="editScheduleForm">
        {% csrf_token %}

        <div class="mb-4">
            <label for="id_subject" class="block text-gray-700 text-sm font-bold mb-2">Subject</label>
            <input type="text" id="id_subject" name="subject" value="{{ form.subject.value }}"
                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>

        <div class="flex gap-5 w-full justify-center items-center">
            <div class="mb-4 w-1/2">
                <label for="id_department" class="block text-gray-700 text-sm font-bold mb-2">Department</label>
                <select name="{{ form.department.html_name }}" id="{{ form.department.id_for_label }}"
                    class="input input-bordered w-full">
                    {% for value, label in form.department.field.choices %}
                    {% if form.department.value|stringformat:"s" == value|stringformat:"s" %}
                    <option value="{{ value }}" selected>{{ label }}</option>
                    {% else %}
                    <option value="{{ value }}">{{ label }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>

            <div class="mb-4 w-1/2">
                <label for="id_schedule_time" class="block text-gray-700 text-sm font-bold mb-2">Schedule Time</label>
                <input type="datetime-local" id="id_schedule_time" name="schedule_time"
                    value="{{ form.schedule_time.value|date:'Y-m-d\\TH:i' }}"
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
        </div>

        <div class="mb-4">
            <label for="id_content" class="block text-gray-700 text-sm font-bold mb-2">Message</label>
            {{ form.content }}
        </div>

        {{ form.media }}

        <button type="submit"
            class=" border btn-sm md:btn-md btn bg-orange-500 hover:bg-orange-600 hover:text-orange-100 rounded-lg text-white text-sm md:text-base">Save</button>
        <button type="button"
            class="border btn-sm md:btn-md btn bg-red-600 hover:bg-red-700 hover:text-red-100 rounded-lg text-white text-sm  md:text-base"
            onclick="closeEditModal()">Cancel</button>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function () {
        $('#editScheduleForm').submit(function (event) {
            event.preventDefault();
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
            let formData = $(this).serialize();
            $.ajax({
                url: $(this).attr('action'),
                method: 'POST',
                data: formData,
                success: function (response) {
                    if (response.success) {
                        Swal.fire({
                            icon: 'success',
                            title: 'Saved!',
                            text: 'The message has been successfully saved.',
                            confirmButtonColor: '#DD6B20'
                        }).then(() => {
                            window.location.reload();
                        });
                    } else {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error!',
                            text: response.message,
                            confirmButtonColor: '#d33'
                        });
                    }
                },
                error: function (xhr, status, error) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: 'An error occurred while saving the message. Please try again.',
                        confirmButtonColor: '#d33'
                    });
                }
            });
        });
    });

    function closeEditModal() {
        window.history.back();
    }
</script>
{% endblock content %}

dashboard/templates/email_manager.html
{% extends 'base.html' %}
{% block meta %}
<title>Email Manager</title>
{% endblock meta %}

{% block content %}
<div class="m-10 text-2xl font-semibold">
    Dashboard
</div>
<div class="m-10 bg-white shadow-md rounded flex">
    <div class="w-1/4 p-4 border-r">
        <button id="showSent"
            class="w-full mt-10 text-gray-600 border px-4 py-2 rounded mb-2 text-left hover:border-animate  text-sm md:text-base">Sent</button>
        <button id="showScheduled"
            class="w-full text-gray-600 border px-4 py-2 rounded text-left hover:border-animate  text-sm md:text-base">Scheduled</button>
    </div>
    <div class="w-3/4 p-4">
        <table id="emailTable" class="display m-20" style="width:100%">
            <thead class="bg-gray-950 text-white">
                <tr>
                    <th class="subject-col">Subject</th>
                    <th class="time-col">Schedule Time</th>
                </tr>
            </thead>
            <tbody>
                <!-- Table rows will be dynamically loaded here -->
            </tbody>
        </table>
        <div id="emailDetails" class="bg-gray-50 p-4 rounded shadow-sm hidden">
            <div class="flex justify-between">
                <button id="backButton"
                    class="border btn-xs md:btn-sm btn btn-neutral rounded-lg text-white text-sm md:text-base">Back</button>
                <div>
                    <button id="editButton"
                        class=" border btn-xs md:btn-sm btn bg-orange-500 hover:bg-orange-600 hover:text-orange-100 rounded-lg text-white text-sm md:text-base">Edit</button>
                    <button onclick="showDeleteModal()" id="deleteButton"
                        class=" border btn-xs md:btn-sm btn bg-red-600 hover:bg-red-700 hover:text-red-100 rounded-lg text-white  text-sm md:text-base">Delete</button>
                </div>
            </div>

            <div class="text-xl font-semibold mt-5" id="emailSubject"></div>
            <span class="font-light text-sm" id="emailScheduleTime"></span>
            <div class="my-2"><strong>Sent to:</strong> <span id="emailDepartment"></span></div>
            <div id="emailContent" class="ck-content my-5"></div>
        </div>
    </div>

    <!-- Modal for Delete Confirmation -->
    <dialog id="my_modal_1" class="modal">
        <div class="modal-box">
            <h3 class="font-bold text-lg">Confirm Deletion</h3>
            <p class="py-4">Are you sure you want to delete this data?</p>
            <div class="modal-action">
                <form method="post" id="deleteForm">
                    {% csrf_token %}
                    <button type="submit"
                        class="btn bg-red-600 hover:bg-red-700 hover:text-red-100 rounded-lg text-white  text-sm md:text-base"
                        id="confirmDeleteButton">Confirm</button>
                    <button type="button" class="btn btn-neutral rounded-lg text-white  text-sm md:text-base"
                        onclick="closeDeleteModal()">Cancel</button>
                </form>
            </div>
        </div>
    </dialog>


    <style>
        .dataTables_length {
            display: none !important;
        }

        .subject-col {
            width: 66.66%;
        }

        .time-col {
            width: 33.33%;
        }

        .hover\:border-animate {
            position: relative;
            overflow: hidden;
            z-index: 1;
        }

        .hover\:border-animate::before,
        .hover\:border-animate::after {
            content: '';
            position: absolute;
            border: 2px solid black;
            width: 100%;
            height: 100%;
            z-index: -1;
            transition: transform 0.5s ease;
            transform: scaleX(0) scaleY(0);
        }

        .hover\:border-animate::before {
            top: 0;
            left: 0;
            transform-origin: bottom left;
        }

        .hover\:border-animate::after {
            bottom: 0;
            right: 0;
            transform-origin: top right;
        }

        .hover\:border-animate:hover::before,
        .hover\:border-animate:hover::after {
            transform: scaleX(1) scaleY(1);
        }

        .dt-search label {
            margin-right: 10px;
            font-weight: 600;
        }

        .dt-search input[type="search"]:focus {
            border-color: #DD6B20;
            outline: none;
            box-shadow: 0 0 0 1px #DD6B20;
        }
    </style>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function () {
            let emailTable = $('#emailTable').DataTable({
                paging: true,
                searching: true,
                pageLength: 10,
                ordering: true,
                info: false,
                lengthChange: false,
                language: {
                    "paginate": {
                        "previous": "Prev",
                        "next": "Next"
                    }
                },
                ajax: {
                    url: '/emails/sent/',
                    dataSrc: 'emails'
                },
                columns: [
                    { data: 'subject' },
                    { data: 'schedule_time' }
                ]
            });

            $('#showSent').click(function () {
                emailTable.ajax.url('/emails/sent/').load();
                $('#emailTable_wrapper').removeClass('hidden');
                $('#emailDetails').addClass('hidden');
                $('#editButton').hide();
            });

            $('#showScheduled').click(function () {
                emailTable.ajax.url('/emails/scheduled/').load();
                $('#emailTable_wrapper').removeClass('hidden');
                $('#emailDetails').addClass('hidden');
                $('#editButton').show();
            });

            $('#emailTable tbody').on('click', 'tr', function () {
                let data = emailTable.row(this).data();
                fetchEmailDetails(data.id);
            });

            function fetchEmailDetails(id) {
                $('#emailTable_wrapper').addClass('hidden');
                $.ajax({
                    url: `/emails/detail/${id}/`,
                    method: 'GET',
                    success: function (data) {
                        $('#emailDepartment').text(data.department);
                        $('#emailSubject').text(data.subject);
                        $('#emailContent').html(data.content);
                        $('#emailScheduleTime').text(data.schedule_time);
                        $('#emailDetails').removeClass('hidden');

                        $('#backButton').click(function () {
                            $('#emailDetails').addClass('hidden');
                            $('#emailTable_wrapper').removeClass('hidden');
                        });

                        // Set the delete form action URL to include the email ID
                        $('#deleteForm').attr('action', `/emails/delete/${id}/`);

                        $('#editButton').off('click').on('click', function () {
                            window.location.href = `/edit-schedule-email/${id}/`;
                        });
                    }
                });
            }

            $('#deleteForm').submit(function (event) {
                event.preventDefault(); // Prevent default form submission
                const form = $(this);
                $.ajax({
                    url: form.attr('action'),
                    method: 'POST',
                    data: form.serialize(),
                    success: function (response) {
                        if (response.status === 'success') {
                            closeDeleteModal();
                            Swal.fire({
                                icon: 'success',
                                title: 'Deleted!',
                                text: 'The email has been deleted successfully.',
                                confirmButtonColor: '#DD6B20'
                            }).then(() => {
                                window.location.reload();
                            });
                        } else {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error!',
                                text: response.message,
                                confirmButtonColor: '#d33'
                            });
                        }
                    },
                    error: function () {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error!',
                            text: 'An error occurred while deleting the email. Please try again.',
                            confirmButtonColor: '#d33'
                        });
                    }
                });
            });
        });

        function showDeleteModal() {
            const deleteModal = document.getElementById('my_modal_1');
            deleteModal.showModal();
        }

        function closeDeleteModal() {
            const deleteModal = document.getElementById('my_modal_1');
            deleteModal.close();
        }
    </script>
</div>
{% endblock content %}